local M = {}

M.highlights = function(c)
  return {
    Normal = { fg = c.foreground, bg = c.background },
    StatusLineNC = { bg = c.background, fg = c.background },
    StatusLine = { bg = "NONE", fg = "NONE" },
    SignColumn = { bg = c.background, fg = c.background },
    MsgArea = { fg = c.foreground, bg = c.background },
    ModeMsg = { fg = c.foreground, bg = c.background },
    MsgSeparator = { fg = c.foreground, bg = c.background },
    SpellBad = { fg = c.yellow },
    SpellCap = { fg = c.blue },
    SpellLocal = { fg = c.orange },
    SpellRare = { fg = c.blue },
    NormalNC = { fg = c.foreground, bg = c.background },
    Pmenu = { fg = c.foreground, bg = c.background },
    PmenuSel = { fg = c.background, bg = c.orange },
    PmenuSbar = { bg = c.background },
    PmenuThumb = { bg = c.yellow },
    WildMenu = { fg = c.light_green, bg = c.orange },
    CursorLineNr = { fg = c.cursorline },
    Folded = { fg = c.orange, bg = c.background },
    FoldColumn = { fg = c.orange, bg = c.background },
    LineNr = { fg = c.dark_pink, bg = c.background },
    FloatBorder = { fg = c.border },
    Whitespace = { fg = c.light_red },
    VertSplit = { fg = c.border },
    CursorLine = { bg = c.cursorline },
    CursorColumn = { bg = c.background },
    ColorColumn = { bg = c.background },
    NormalFloat = { bg = c.background },
    Visual = { bg = c.dark_purple, fg = c.foreground },
    VisualNOS = { bg = c.background },
    WarningMsg = { fg = c.red, bg = c.background },
    DiffAdd = { bg = c.background, fg = c.orange },
    DiffChange = { bg = c.background, fg = c.purple },
    DiffDelete = { bg = c.background, fg = c.red },
    QuickFixLine = { bg = c.background_contrast },
    MatchParen = { fg = c.orange, bg = c.background },
    Cursor = { fg = c.foreground, bg = c.cursor },
    lCursor = { fg = c.foreground, bg = c.cursor },
    CursorIM = { fg = c.foreground, bg = c.cursor },
    TermCursor = { fg = c.foreground, bg = c.cursor },
    TermCursorNC = { fg = c.foreground, bg = c.cursor },
    Conceal = { fg = c.orange, bg = c.background },
    Directory = { fg = c.orange },
    SpecialKey = { fg = c.orange },
    Title = { fg = c.orange, bold = true },
    ErrorMsg = { fg = c.light_red, bg = c.background },
    Search = { fg = c.background, bg = c.foreground },
    IncSearch = { fg = c.background, bg = c.pink },
    Substitute = { fg = c.red, bg = c.blue },
    MoreMsg = { fg = c.purple },
    Question = { fg = c.purple },
    EndOfBuffer = { fg = c.background },
    NonText = { fg = c.light_red },
    Variable = { fg = c.purple },
    String = { fg = c.yellow },
    Character = { fg = c.pink },
    Number = { fg = c.red },
    Boolean = { fg = c.blue, bold = true },
    Float = { fg = c.purple },
    Identifier = { fg = c.purple },
    Function = { fg = c.blue },
    Operator = { fg = c.blue },
    Type = { fg = c.purple },
    StorageClass = { fg = c.light_green },
    Structure = { fg = c.blue },
    Constant = { fg = c.purple },
    Comment = { fg = c.comment, italic = true },
    Conditional = { fg = c.blue },
    Typedef = { fg = c.blue },
    Keyword = { fg = c.blue },
    Statement = { fg = c.blue },
    Repeat = { fg = c.blue },
    Label = { fg = c.orange },
    Exception = { fg = c.blue },
    Include = { fg = c.blue },
    PreProc = { fg = c.blue },
    Define = { fg = c.blue },
    Macro = { fg = c.blue },
    PreCondit = { fg = c.blue },
    Special = { fg = c.blue },
    SpecialChar = { fg = c.foreground },
    Tag = { fg = c.orange },
    Debug = { fg = c.light_red },
    Delimiter = { fg = c.foreground },
    SpecialComment = { fg = c.yellow },
    Ignore = { fg = c.light_green, bg = c.background },
    Todo = { fg = c.light_red, bg = c.background },
    Error = { fg = c.light_red, bg = c.background },
    TabLineFill = { fg = c.foreground, bg = c.background },
    TabLineSel = { fg = c.foreground, bg = c.background },
    TabLine = { fg = c.yellow, bg = c.background },
    healthError = { fg = c.red },
    healthSuccess = { fg = c.green },
    healthWarning = { fg = c.orange },

    -- Treesitter
    ["@attribute"] = { fg = c.orange },
    ["@boolean"] = { fg = c.blue },
    ["@character"] = { fg = c.orange },
    ["@comment"] = { fg = c.comment, italic = true },
    ["@conditional"] = { fg = c.light_red },
    ["@constant"] = { fg = c.blue },
    ["@constant.builtin"] = { fg = c.orange },
    ["@constant.macro"] = { fg = c.red },
    ["@constructor"] = { fg = c.orange },
    ["@exception"] = { fg = c.green },
    ["@field"] = { fg = c.light_red },
    ["@float"] = { fg = c.green },
    ["@function"] = { fg = c.light_red },
    ["@function.builtin"] = { fg = c.yellow },
    ["@function.macro"] = { fg = c.yellow },
    ["@include"] = { fg = c.dark_purple },
    ["@operator"] = { fg = c.light_green },
    ["@keyword"] = { fg = c.purple },
    ["@keyword.function"] = { fg = c.orange },
    ["@keyword.operator"] = { fg = c.pink, italic = true },
    ["@keyword.return"] = { fg = c.orange },
    ["@label"] = { fg = c.orange },
    ["@method"] = { fg = c.pink },
    ["@namespace"] = { fg = c.dark_purple },
    ["@number"] = { fg = c.red },
    ["@parameter"] = { fg = c.light_red },
    ["@parameter.reference"] = { fg = c.dark_purple },
    ["@property"] = { fg = c.light_red },
    ["@punctuation.delimiter"] = { fg = c.light_green },
    ["@punctuation.bracket"] = { fg = c.light_green },
    ["@punctuation.special"] = { fg = c.light_green },
    ["@repeat"] = { fg = c.light_red },
    ["@string"] = { fg = c.yellow },
    ["@string.regex"] = { fg = c.yellow },
    ["@string.escape"] = { fg = c.orange },
    ["@string.special"] = { fg = c.orange },
    ["@symbol"] = { fg = c.light_red },
    ["@tag"] = { fg = c.orange },
    ["@tag.attribute"] = { fg = c.light_red },
    ["@tag.delimiter"] = { fg = c.light_green },
    ["@text"] = { fg = c.light_green },
    ["@text.strong"] = { fg = c.light_green, bold = true },
    ["@text.emphasis"] = { fg = c.light_green, italic = true },
    ["@text.underline"] = { fg = c.purple, underline = true },
    ["@text.strike"] = { fg = c.light_green, strikethrough = true },
    ["@text.title"] = { fg = c.red, bold = true },
    ["@text.literal"] = { fg = c.yellow, italic = true },
    ["@text.uri"] = { fg = c.red, underline = true },
    ["@text.math"] = { fg = c.blue },
    ["@text.reference"] = { fg = c.blue },
    ["@text.environtment"] = { fg = c.purple },
    ["@text.environment.name"] = { fg = c.red },
    ["@text.note"] = { fg = c.green },
    ["@text.warning"] = { fg = c.dark_pink, bg = c.light_red },
    ["@text.danger"] = { fg = c.green },
    ["@type"] = { fg = c.red },
    ["@type.builtin"] = { fg = c.red },
    ["@variable"] = { fg = c.light_green },
    ["@variable.builtin"] = { fg = c.orange },

    -- cmp
    CmpDocumentationBorder = { fg = c.foreground, bg = c.background },
    CmpItemAbbr = { fg = c.foreground, bg = c.background },
    CmpItemAbbrDeprecated = { fg = c.yellow, bg = c.background },
    CmpItemAbbrMatch = { fg = c.light_green, bg = c.background },
    CmpItemAbbrMatchFuzzy = { fg = c.light_green, bg = c.background },
    CmpItemKind = { fg = c.orange, bg = c.background },
    CmpItemMenu = { fg = c.yellow, bg = c.background },

    -- git
    SignAdd           = { fg = c.green, bg = 'NONE' },
    SignChange        = { fg = c.yellow, bg = 'NONE' },
    SignDelete        = { fg = c.red, bg = 'NONE' },
    GitSignsAdd       = { fg = c.green, bg = 'NONE' },
    GitSignsChange    = { fg = c.yellow, bg = 'NONE' },
    GitSignsDelete    = { fg = c.red, bg = 'NONE' },

    -- LSP
    DiagnosticHint = { fg = c.yellow, bg = 'NONE', underline = true },
    DiagnosticSignHint = { fg = c.yellow, bg = 'NONE', underline = false },
    DiagnosticInfo = { fg = c.blue, bg = 'NONE', underline = true },
    DiagnosticSignInfo = { fg = c.blue, bg = 'NONE', underline = false },
    DiagnosticWarn = { fg = c.orange, bg = 'NONE', underline = true },
    DiagnosticSignWarn = { fg = c.orange, bg = 'NONE', underline = false },
    DiagnosticOther = { fg = c.red, bg = 'NONE', underline = true },
    DiagnosticError = { fg = c.red, bg = 'NONE', underline = true },
    DiagnosticSignError = { fg = c.red, bg = 'NONE', underline = false },
    DiagnosticUnderlineError = { fg = 'NONE', bg = 'NONE', undercurl = true },

    -- Nvim-Tree
    NvimTreeNormal = { fg = c.foreground, bg = c.background_contrast },
    NvimTreeNormalNC = { fg = c.foreground, bg = c.background_contrast },
    NvimTreeRootFolder = { fg = c.yellow },
    NvimTreeExecFile = { fg = c.yellow },
    NvimTreeGitDirty = { fg = c.light_red },
    NvimTreeGitNew = { fg = c.orange },
    NvimTreeGitDeleted = { fg = c.red },
    NvimTreeSpecialFile = { fg = c.blue },
    NvimTreeIndentMarker = { fg = c.dark_pink },
    NvimTreeImageFile = { fg = c.foreground },
    NvimTreeSymlink = { fg = c.light_green },
    NvimTreeFolderIcon = { fg = c.orange, bg = c.background },
    NvimTreeFolderName = { fg = c.foreground },
    NvimTreeOpenedFile = { bg = c.green },
    NvimTreeOpenedFolderName = { fg = c.yellow },
    NvimTreeEmptyFolderName = { fg = c.yellow },
    NvimTreeStatusLineNC = { bg = c.background, fg = c.background },

    -- Packer
    packerString = { fg = c.blue, bg = 'NONE' },
    packerOutput = { fg = c.orange, bg = 'NONE' },
    packerSuccess = { fg = c.green, bg = 'NONE' },
    packerStatusSuccess = { fg = c.yellow, bg = 'NONE' },
    packerHash = { fg = c.yellow, bg = 'NONE' },
    packerRelDate = { fg = c.blue, bg = 'NONE' },

    -- Telescope
    TelescopeSelection = { fg = 'NONE', bg = c.cursorline },
    TelescopeSelectionCaret = { fg = c.pink, bg = c.cursorline },
    TelescopeBorder = { fg = c.border, bg = 'NONE' },
    TelescopeNormal = { fg = c.foreground, bg = 'NONE' },
    TelescopeMatching = { fg = c.orange, bg = 'NONE', italic = true },
    TelescopePromptTitle = { fg = c.orange, bg = 'NONE', bold = true },
    TelescopeResultsTitle = { fg = c.orange, bg = 'NONE', bold = true },
    TelescopePreviewTitle = { fg = c.orange, bg = 'NONE', bold = true },
    TelescopePromptPrefix = { fg = c.pink, bg = 'NONE' },
    TelescopePromptCounter = { fg = c.pink, bg = 'NONE' },

  }
end

return M
